version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@host.docker.internal:5432/task?sslmode=disable
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint:
      [
        "./migrate.sh"
      ]
    command: [ "/app/task", "serve" ]
