// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"encoding/json"
	"time"
)

type Keys struct {
	ID         int32     `json:"id"`
	Key        string    `json:"key"`
	UsageCount int32     `json:"usage_count"`
	CreatedAt  time.Time `json:"created_at"`
}

type Sites struct {
	ID        int32           `json:"id"`
	Url       string          `json:"url"`
	MetaData  json.RawMessage `json:"meta_data"`
	CreatedAt time.Time       `json:"created_at"`
}
