// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateKey(ctx context.Context, key string) (Keys, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Sites, error)
	GetKey(ctx context.Context, key string) (Keys, error)
	GetRandomKey(ctx context.Context) (Keys, error)
	GetSiteByURL(ctx context.Context, url string) (Sites, error)
	IncreaseKeyUsageCount(ctx context.Context, id int32) error
}

var _ Querier = (*Queries)(nil)
